version: '3.4'

services:
  databank: # service name
    image: databank # image name
    # container_name:  databank # container name
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 5000:5000
  webserver:
    image: nginx:latest
    container_name: nginx   
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - databank # service name
    ports:
      - 80:5000
